_items = [
	// ACE
	"ACE_RangeTable_82mm",
	"ACE_artilleryTable",
	"ACE_CableTie",
	"ACE_DefusalKit",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_Fortify",
	"ACE_M26_Clacker",
	"ACE_Flashlight_KSF1",
	"ACE_MapTools",
	"ace_marker_flags_black",
	"ace_marker_flags_blue",
	"ace_marker_flags_green",
	"ace_marker_flags_orange",
	"ace_marker_flags_purple",
	"ace_marker_flags_red",
	"ace_marker_flags_white",
	"ace_marker_flags_yellow",
	"ACE_rope12",
	"ACE_rope15",
	"ACE_rope18",
	"ACE_rope27",
	"ACE_rope3",
	"ACE_rope36",
	"ACE_rope6",
	"ACE_SpareBarrel_Item",
	"ACE_wirecutter",
	"ACRE_SEM70",
	"SPE_ToolKit",

	//ACE and KAT Medical
	"ACE_adenosine",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_packingBandage",
	"ACE_quikclot",
	"ACE_bloodIV",
	"ACE_bloodIV_250",
	"ACE_bloodIV_500",
	"ACE_bodyBag",
	"ACE_epinephrine",
	"ACE_morphine",
	"ACE_splint",
	"ACE_surgicalKit",
	"ACE_tourniquet",
	"kat_IV_16",
	"kat_aatKit",
	"kat_amiodarone",
	"kat_CarbonateItem",
	"kat_atropine",
	"kat_BVM",
	"kat_CaffeineItem",
	"kat_chestSeal",
	"kat_EACA",
	"kat_etomidate",
	"kat_fentanyl",
	"kat_flumazenil",
	"kat_guedel",
	"kat_ketamine",
	"kat_lidocaine",
	"kat_lorazepam",
	"kat_nalbuphine",
	"kat_naloxone",
	"kat_nitroglycerin",
	"kat_norepinephrine",
	"kat_PervitinItem",
	"kat_phenylephrine",
	"kat_stethoscope",
	"kat_TXA",

	// Googles
	"G_SPE_Binoculars",
	"G_SPE_Cigarette_Strike_Outs",
	"G_SPE_Cigar_Moza",
	"G_SPE_Ful_Vue_Reinforced",
	"G_SPE_Ful_Vue",
	"G_SPE_SWDG_Goggles",
	"G_SPE_Polar_Goggles",
	"G_SPE_Pipe_Sir_Winston",
	"G_SPE_Sunglasses_US_Red",
	"G_SPE_Sunglasses_US_Yellow",
	"G_SPE_GER_Headset",
	"fow_g_gloves4",
	"fow_g_gloves5",
	"fow_g_gloves6",
	"fow_g_gloves2",
	"fow_g_gloves1",
	"fow_g_gloves3",
	"fow_g_glasses4",

	// NVG
	"SPE_GER_Headset",
	"LIB_GER_Gloves4",
	"LIB_GER_Gloves5",
	"LIB_GER_Gloves2",
	"LIB_GER_Gloves1",
	"LIB_GER_Gloves3",

	// Other
	"ItemMap",
	"SPE_US_ItemCompass",
	"SPE_US_ItemWatch"
];