//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class STAF_pmc_vehicles {
      units[] = {
        "STAF_md500",
        "STAF_md500_defender",
        "STAF_uh60m",
        "STAF_hexacopter",
        "STAF_hexacopter_ammo",
        "STAF_hexacopter_medical",
        "STAF_hexacopter_explosive",
        "STAF_rubberboat",
        "STAF_truck_transport",
        "STAF_truck_box",
        "STAF_truck_fuel",
        "STAF_truck_covered",
        "STAF_offroad",
        "STAF_offroad_pickup",
        "STAF_suv",
        "STAF_suv_2",
        "STAF_caiman",
        "STAF_caiman_woodland",
        "STAF_caiman_desert",
        "STAF_husky_woodland",
        "STAF_husky_desert",
        "STAF_lsv",
        "STAF_quadcopter",
        "STAF_md500_opf",
        "STAF_md500_defender_opf",
        "STAF_uh60m_opf",
        "STAF_hexacopter_opf",
        "STAF_hexacopter_ammo_opf",
        "STAF_hexacopter_medical_opf",
        "STAF_hexacopter_explosive_opf",
        "STAF_rubberboat_opf",
        "STAF_truck_transport_opf",
        "STAF_truck_box_opf",
        "STAF_truck_fuel_opf",
        "STAF_truck_covered_opf",
        "STAF_offroad_opf",
        "STAF_offroad_pickup_opf",
        "STAF_suv_opf",
        "STAF_suv_2_opf",
        "STAF_caiman_opf",
        "STAF_caiman_woodland_opf",
        "STAF_caiman_desert_opf",
        "STAF_husky_woodland_opf",
        "STAF_husky_desert_opf",
        "STAF_lsv_opf",
        "STAF_quadcopter_opf",
        "STAF_md500_ind",
        "STAF_md500_defender_ind",
        "STAF_uh60m_ind",
        "STAF_hexacopter_ind",
        "STAF_hexacopter_ammo_ind",
        "STAF_hexacopter_medical_ind",
        "STAF_hexacopter_explosive_ind",
        "STAF_rubberboat_ind",
        "STAF_truck_transport_ind",
        "STAF_truck_box_ind",
        "STAF_truck_fuel_ind",
        "STAF_truck_covered_ind",
        "STAF_offroad_ind",
        "STAF_offroad_pickup_ind",
        "STAF_suv_ind",
        "STAF_suv_2_ind",
        "STAF_caiman_ind",
        "STAF_caiman_woodland_ind",
        "STAF_caiman_desert_ind",
        "STAF_husky_woodland_ind",
        "STAF_husky_desert_ind",
        "STAF_lsv_ind",
        "STAF_quadcopter_ind"
      };
      weapons[] = {};
      requiredAddons[] = {"A3_Soft_F_Gamma","A3_Functions_F","A3_Soft_F","A3_Soft_F_Beta","A3_Soft_F_Bootcamp","A3_Soft_F_epc","A3_Armor_F","A3_Armor_F_Beta","A3_Armor_F_EPB","A3_Armor_F_EPC","A3_Armor_F_Gamma","A3_Air_F","A3_Air_F_Gamma","A3_Boat_F","A3_Boat_F_Beta","A3_Boat_F_EPC","A3_Boat_F_Gamma","A3_Static_F","A3_Static_F_Beta","A3_Static_F_Gamma","staf_framework"};
      requiredVersion = 1.62;
      author = "STAF";
      url = "http://www.stafclan.com";
    };
};
