_unit = _this select 0;
_startUniform = ["STAF_Scientist"];

if ((uniform _unit) in _startUniform) then {
    _magazineStore = magazines _unit;

    removeUniform _unit;
    removeHeadgear _unit;
    removevest _unit;
    _uniform = [
                  "U_B_CombatUniform_mcam",
                  "U_B_CombatUniform_mcam_tshirt",
                  "U_B_CTRG_1",
                  "U_B_CTRG_2",
                  "U_B_CTRG_3",
                  "U_BG_Guerrilla_6_1",
                  "U_BG_Guerilla1_1",
                  "U_BG_Guerilla2_2",
                  "U_BG_Guerilla2_1",
                  "U_BG_Guerilla2_3",
                  "U_I_G_Story_Protagonist_F",
                  "U_B_T_Soldier_F",
                  "U_B_T_Soldier_AR_F",
                  "U_B_GEN_Commander_F",
                  "U_B_GEN_Soldier_F",
                  "STAF_U_BG_Guerilla2_1_Steppentarn",
                  "STAF_U_BG_Guerilla2_1_Flora_Coyote",
                  "STAF_U_BG_Guerilla2_1_Choc_Chip",
                  "STAF_U_BG_Guerrilla_4_1_tan_vegetato",
                  "STAF_U_BG_Guerrilla_4_1_tan_vegetato",
                  "STAF_U_BG_Guerrilla_6_1_ERDL_Black",
                  "tacs_Uniform_Combat_LS_BS_GP_BB",
                  "tacs_Uniform_Combat_LS_BS_GP_TB",
                  "tacs_Uniform_Combat_LS_BS_TP_BB",
                  "tacs_Uniform_Combat_LS_BS_TP_TB",
                  "tacs_Uniform_Combat_LS_GS_BP_BB",
                  "tacs_Uniform_Combat_LS_GS_TP_BB",
                  "tacs_Uniform_Combat_LS_BS_DGP_BB",
                  "tacs_Uniform_Combat_LS_TS_BP_BB",
                  "tacs_Uniform_Combat_LS_TS_GP_BB",
                  "tacs_Uniform_Combat_LS_TS_GP_TB",
                  "tacs_Uniform_Combat_LS_CDBS_GP_TB",
                  "tacs_Uniform_Combat_LS_CLBS_GP_BB",
                  "tacs_Uniform_Combat_LS_CLRS_TP_BB",
                  "tacs_Uniform_Combat_LS_CPS_BP_BB",
                  "tacs_Uniform_Combat_RS_BS_GP_BB",
                  "tacs_Uniform_Combat_RS_BS_GP_TB",
                  "tacs_Uniform_Combat_RS_BS_TP_BB",
                  "tacs_Uniform_Combat_RS_BS_TP_TB",
                  "tacs_Uniform_Combat_RS_GS_BP_BB",
                  "tacs_Uniform_Combat_RS_GS_TP_BB",
                  "tacs_Uniform_Combat_RS_BS_DGP_BB",
                  "tacs_Uniform_Combat_RS_TS_BP_BB",
                  "tacs_Uniform_Combat_RS_TS_GP_BB",
                  "tacs_Uniform_Combat_RS_TS_GP_TB",
                  "tacs_Uniform_Combat_RS_CDBS_GP_TB",
                  "tacs_Uniform_Combat_RS_CLBS_GP_BB",
                  "tacs_Uniform_Combat_RS_CLRS_TP_BB",
                  "tacs_Uniform_Combat_RS_CPS_BP_BB",
                  "tacs_Uniform_Garment_LS_BS_BP_BB",
                  "tacs_Uniform_Garment_LS_BS_GP_BB",
                  "tacs_Uniform_Garment_LS_OS_EP_TB",
                  "tacs_Uniform_Garment_LS_GS_GP_BB",
                  "tacs_Uniform_Garment_LS_GS_BP_BB",
                  "tacs_Uniform_Garment_LS_GS_EP_TB",
                  "tacs_Uniform_Garment_LS_ES_EP_TB",
                  "tacs_Uniform_Garment_LS_ES_BP_BB",
                  "tacs_Uniform_Garment_LS_ES_GP_BB",
                  "tacs_Uniform_Garment_LS_TS_TP_TB",
                  "tacs_Uniform_Garment_LS_GS_TP_TB",
                  "tacs_Uniform_Garment_LS_TS_GP_BB",
                  "tacs_Uniform_Garment_LS_OS_TP_TB",
                  "tacs_Uniform_Garment_LS_TS_BP_BB",
                  "tacs_Uniform_Garment_RS_BS_BP_BB",
                  "tacs_Uniform_Garment_RS_BS_GP_BB",
                  "tacs_Uniform_Garment_RS_OS_EP_TB",
                  "tacs_Uniform_Garment_RS_GS_GP_BB",
                  "tacs_Uniform_Garment_RS_GS_BP_BB",
                  "tacs_Uniform_Garment_RS_GS_EP_TB",
                  "tacs_Uniform_Garment_RS_ES_EP_TB",
                  "tacs_Uniform_Garment_RS_ES_BP_BB",
                  "tacs_Uniform_Garment_RS_ES_GP_BB",
                  "tacs_Uniform_Garment_RS_TS_TP_TB",
                  "tacs_Uniform_Garment_RS_GS_TP_TB",
                  "tacs_Uniform_Garment_RS_TS_GP_BB",
                  "tacs_Uniform_Garment_RS_OS_TP_TB",
                  "tacs_Uniform_Garment_RS_TS_BP_BB"
                  ] call BIS_fnc_selectRandom;
    _headGear = [
                  "H_Bandanna_gry",
                  "H_Bandanna_blu",
                  "H_Bandanna_cbr",
                  "H_Bandanna_khk_hs",
                  "H_Bandanna_khk",
                  "H_Bandanna_sgg",
                  "H_Bandanna_sand",
                  "H_Bandanna_camo",
                  "H_Watchcap_blk",
                  "H_Watchcap_cbr",
                  "H_Watchcap_camo",
                  "H_Watchcap_khk",
                  "H_Cap_grn_BI",
                  "H_Cap_grn",
                  "H_Cap_blk",
                  "H_Cap_blu",
                  "H_Cap_blk_CMMG",
                  "H_Cap_oli",
                  "H_Cap_oli_hs",
                  "H_Cap_tan",
                  "H_Cap_headphones",
                  "H_Bandanna_mcamo",
                  "H_Bandanna_surfer_blk",
                  "H_Bandanna_surfer_grn",
                  "H_Cap_blk_raven",
                  "H_Cap_brn_SPECOPS",
                  "ABU_Helmet1",
                  "ABU_Helmet2",
                  "M81_Helmet1",
                  "M81_Helmet2",
                  "M90_Helmet1",
                  "M90_Helmet2",
                  "M90d_Helmet1",
                  "M90d_Helmet2",
                  "MCB_Helmet1",
                  "MCB_Helmet2",
                  "MC_Helmet1",
                  "MC_Helmet2",
                  "OGA_G_Helmet1",
                  "OGA_G_Helmet2",
                  "OGA_Helmet1",
                  "OGA_Helmet2",
                  "VSM_BackwardsHat_Peltor_black",
                  "VSM_BackwardsHat_Peltor_CMMG",
                  "VSM_BackwardsHat_Peltor_OG",
                  "VSM_BackwardsHat_Peltor_Sero",
                  "VSM_BackwardsHat_Peltor_tan",
                  "VSM_Beanie_Black",
                  "VSM_Beanie_OD",
                  "VSM_Beanie_tan",
                  "VSM_Bowman_cap_balaclava_Black",
                  "VSM_Bowman_cap_balaclava_Olive",
                  "VSM_Bowman_cap_balaclava_tan",
                  "VSM_Bowman_cap_Black",
                  "VSM_Bowman_cap_Olive",
                  "VSM_Bowman_cap_tan",
                  "VSM_Mich2000_AOR1",
                  "VSM_Mich2000_M81",
                  "VSM_Mich2000_Multicam",
                  "VSM_Mich2000_MulticamTropic",
                  "VSM_Mich2000_OCP",
                  "VSM_Mich2000_OGA_OD",
                  "VSM_Mich2000_OGA",
                  "VSM_Mich2000_CamoSprayOD",
                  "VSM_Mich2000_CamoSprayTan",
                  "VSM_Mich2000_ProjectHonor",
                  "VSM_Mich2000_AOR1",
                  "VSM_OPS_aor1",
                  "VSM_OPS",
                  "VSM_Black_OPS",
                  "VSM_M81_OPS",
                  "VSM_OPS_multicam",
                  "VSM_multicamtropic_OPS",
                  "VSM_ocp_OPS",
                  "VSM_od_spray_OPS",
                  "VSM_OGA_od_OPS",
                  "VSM_OGA_OPS",
                  "VSM_ProjectHonor_OPS",
                  "VSM_tan_spray_OPS",
                  "VSM_ops_2_aor1",
                  "VSM_ops_2",
                  "VSM_Black_ops_2",
                  "VSM_M81_ops_2",
                  "VSM_ops_2_multicam",
                  "VSM_multicamtropic_ops_2",
                  "VSM_ocp_ops_2",
                  "VSM_od_spray_ops_2",
                  "VSM_OGA_od_ops_2",
                  "VSM_OGA_ops_2",
                  "VSM_ProjectHonor_ops_2",
                  "VSM_tan_spray_ops_2"
                  ] call BIS_fnc_selectRandom;
    _vest = [
                  "V_PlateCarrier1_blk",
                  "V_PlateCarrier1_rgr_noflag_F",
                  "V_PlateCarrier2_blk",
                  "V_PlateCarrier2_rgr_noflag_F",
                  "V_Chestrig_blk",
                  "V_Chestrig_rgr",
                  "V_Chestrig_khk",
                  "V_Chestrig_oli",
                  "V_TacVest_blk",
                  "V_TacVest_brn",
                  "V_TacVest_camo",
                  "V_TacVest_khk",
                  "V_TacVest_oli",
                  "tacs_Vest_Tactical_DarkBlack",
                  "V_I_G_resistanceLeader_F",
                  "ABU_Vest_1",
                  "ABU_Vest_2",
                  "ABU_Vest_3",
                  "ABU_Vest_4",
                  "AOR1_Vest_1",
                  "AOR1_Vest_2",
                  "AOR1_Vest_3",
                  "AOR1_Vest_4",
                  "M81_Vest_1",
                  "M81_Vest_2",
                  "M81_Vest_3",
                  "M81_Vest_4",
                  "M90_Vest_1",
                  "M90_Vest_2",
                  "M90_Vest_3",
                  "M90_Vest_4",
                  "M90d_Vest_1",
                  "M90d_Vest_2",
                  "M90d_Vest_3",
                  "M90d_Vest_4",
                  "VSM_MBSS_BLK",
                  "VSM_MBSS_CB",
                  "VSM_MBSS_Green",
                  "VSM_MBSS_Tan",
                  "VSM_MBSS_PACA_BLK",
                  "VSM_MBSS_PACA_CB",
                  "VSM_MBSS_PACA_Green",
                  "VSM_MBSS_PACA_Tan",
                  "MCB_Vest_1",
                  "MCB_Vest_2",
                  "MCB_Vest_3",
                  "MCB_Vest_4",
                  "MC_Vest_1",
                  "MC_Vest_2",
                  "MC_Vest_3",
                  "MC_Vest_4",
                  "OGA_G_Vest_1",
                  "OGA_G_Vest_2",
                  "OGA_G_Vest_3",
                  "OGA_G_Vest_6",
                  "OGA_Vest_1",
                  "OGA_Vest_2",
                  "OGA_Vest_3",
                  "OGA_Vest_6"
            ] call BIS_fnc_selectRandom;
    _unit addHeadgear _headGear;
    _unit addUniform _uniform;
    _unit addvest _vest;

    {_unit addMagazine _x} forEach _magazineStore;

    /*for "_i" from 1 to 9 do {_unit addItem "30Rnd_556x45_Stanag";};
    for "_i" from 1 to 2 do {_unit addItem "KA_17Rnd_9x19_Mag";};
    for "_i" from 1 to 2 do {_unit addItem "SmokeShell";};
    _unit addItem "SmokeShellGreen";
    for "_i" from 1 to 2 do {_unit addItem "HandGrenade";};*/
    save3DENInventory [_unit];
}
else {
};
