//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class STAF_cup_additions_women {
      units[] = {
        "STAF_Max_woman1_RU",
        "STAF_Max_woman1_CHR",
        "STAF_Max_woman1_Vanilla",
        "STAF_Max_woman2_RU",
        "STAF_Max_woman2_CHR",
        "STAF_Max_woman2_Vanilla",
        "STAF_Max_woman3_RU",
        "STAF_Max_woman3_CHR",
        "STAF_Max_woman3_Vanilla",
        "STAF_Max_woman4_RU",
        "STAF_Max_woman4_CHR",
        "STAF_Max_woman4_Vanilla",
        "STAF_Max_Taky_woman1_Afgh",
        "STAF_Max_Taky_woman1_Afr",
        "STAF_Max_Taky_woman1_SA",
        "STAF_Max_Taky_woman1_Tak",
        "STAF_Max_Taky_woman2_Afgh",
        "STAF_Max_Taky_woman2_Afr",
        "STAF_Max_Taky_woman2_SA",
        "STAF_Max_Taky_woman2_Tak",
        "STAF_Max_Taky_woman3_Afgh",
        "STAF_Max_Taky_woman3_Afr",
        "STAF_Max_Taky_woman3_SA",
        "STAF_Max_Taky_woman3_Tak",
        "STAF_Max_Taky_woman4_Afgh",
        "STAF_Max_Taky_woman4_Afr",
        "STAF_Max_Taky_woman4_SA",
        "STAF_Max_Taky_woman4_Tak",
        "STAF_Max_Taky_woman5_Afgh",
        "STAF_Max_Taky_woman5_Afr",
        "STAF_Max_Taky_woman5_SA",
        "STAF_Max_Taky_woman5_Tak",
        "STAF_Max_Tak_woman1_Afgh",
        "STAF_Max_Tak_woman1_Afr",
        "STAF_Max_Tak_woman1_SA",
        "STAF_Max_Tak_woman1_Tak",
        "STAF_Max_Tak_woman2_Afgh",
        "STAF_Max_Tak_woman2_Afr",
        "STAF_Max_Tak_woman2_SA",
        "STAF_Max_Tak_woman2_Tak",
        "STAF_Max_Tak_woman3_Afgh",
        "STAF_Max_Tak_woman3_Afr",
        "STAF_Max_Tak_woman3_SA",
        "STAF_Max_Tak_woman3_Tak",
        "STAF_Max_Tak_woman4_Afgh",
        "STAF_Max_Tak_woman4_Afr",
        "STAF_Max_Tak_woman4_SA",
        "STAF_Max_Tak_woman4_Tak",
        "STAF_Max_Tak_woman5_Afgh",
        "STAF_Max_Tak_woman5_Afr",
        "STAF_Max_Tak_woman5_SA",
        "STAF_Max_Tak_woman5_Tak",
        "STAF_Max_Tak_woman6_Afgh",
        "STAF_Max_Tak_woman6_Afr",
        "STAF_Max_Tak_woman6_SA",
        "STAF_Max_Tak_woman6_Tak",
        "STAF_Max_Tak2_woman1_Afgh",
        "STAF_Max_Tak2_woman1_Afr",
        "STAF_Max_Tak2_woman1_SA",
        "STAF_Max_Tak2_woman1_Tak",
        "STAF_Max_Tak2_woman2_Afgh",
        "STAF_Max_Tak2_woman2_Afr",
        "STAF_Max_Tak2_woman2_SA",
        "STAF_Max_Tak2_woman2_Tak",
        "STAF_Max_Tak2_woman3_Afgh",
        "STAF_Max_Tak2_woman3_Afr",
        "STAF_Max_Tak2_woman3_SA",
        "STAF_Max_Tak2_woman3_Tak",
        "STAF_Max_Tak2_woman4_Afgh",
        "STAF_Max_Tak2_woman4_Afr",
        "STAF_Max_Tak2_woman4_SA",
        "STAF_Max_Tak2_woman4_Tak",
        "STAF_Max_Tak2_woman5_Afgh",
        "STAF_Max_Tak2_woman5_Afr",
        "STAF_Max_Tak2_woman5_SA",
        "STAF_Max_Tak2_woman5_Tak"
      };
      weapons[] = {};
      requiredAddons[] = {"Max_Tak_woman","women"};
      requiredVersion = 1.62;
      author = "STAF";
      url = "http://www.stafclan.com";
    };
};
