//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class STAF_cup_additions_germanarmy {
      units[] = {
        "STAF_CUP_B_Ger_Army_soldier_Jetpilot",
        "STAF_CUP_B_Ger_Army_Fleck_soldier_Pilot",
        "STAF_CUP_B_Ger_Army_Fleck_soldier_Jetpilot",
        "STAF_CUP_B_CH53E_GER",
        "STAF_CFP_B_DEARMY_WDL_CH_53G_Super_Stallion_01",
        "STAF_CUP_B_CH53E_VIV_GER",
        "STAF_CFP_B_DEARMY_WDL_CH_53G_Super_Stallion_VIV_01",
        "STAF_CUP_B_UH1D_GER_KSK_Des",
        "STAF_CUP_B_UH1D_GER_KSK",
        "STAF_CUP_B_UH1D_slick_GER_KSK_Des",
        "STAF_CUP_B_UH1D_slick_GER_KSK",
        "STAF_CUP_B_UH1D_armed_GER_KSK",
        "STAF_CUP_B_UH1D_armed_GER_KSK_Des",
        "STAF_CUP_B_UH1D_gunship_GER_KSK",
        "STAF_CUP_B_UH1D_gunship_GER_KSK_Des",
        "STAF_CUP_B_Dingo_GER_Des",
        "STAF_CUP_B_Dingo_GER_Wdl",
        "STAF_CUP_B_Dingo_GL_GER_Des",
        "STAF_CUP_B_Dingo_GL_GER_Wdl",
        "STAF_AW159_BW_Trop",
        "STAF_AW159_BW_Fleck",
        "STAF_AW159_BW_Trop_Unbewaffnet",
        "STAF_AW159_BW_Fleck_Unbewaffnet",
        "STAF_NH_90_Trop",
        "STAF_NH_90_Fleck",
        "STAF_BW_Euro_Hawk",
        "STAF_BW_Euro_Hawk_Fleck",
        "STAF_BW_EF2000",
        "STAF_BW_EF2000_Fleck",
        "STAF_BW_LKW_Transport_offen_Tropen",
        "STAF_BW_LKW_Transport_Tropen",
        "STAF_BW_LKW_Geraet_Tropen",
        "STAF_BW_LKW_Munition_Tropen",
        "STAF_BW_LKW_Reparatur_Tropen",
        "STAF_BW_LKW_Treibstoff_Tropen",
        "STAF_BW_LKW_Medic_Tropen",
        "STAF_BW_LKW_Transport_offen_fleck",
        "STAF_BW_LKW_Transport_Fleck",
        "STAF_BW_LKW_Geraet_Fleck",
        "STAF_BW_LKW_Munition_Fleck",
        "STAF_BW_LKW_Reparatur_Fleck",
        "STAF_BW_LKW_Treibstoff_Fleck",
        "STAF_BW_LKW_Medic_Fleck",
        "STAF_B_Wiesel_AA",
        "STAF_B_Wiesel_Fleck_AA",
        "STAF_B_Wiesel_AT",
        "STAF_B_Wiesel_Fleck_AT",
        "STAF_B_Wiesel_cannon",
        "STAF_B_Wiesel_Fleck_cannon",
        "STAF_B_Wiesel_scout",
        "STAF_B_Wiesel_Fleck_scout",
        "STAF_Bardelas",
        "STAF_Bardelas_Fleck",
        "STAF_Sholef",
        "STAF_Sholef_Fleck",
        "STAF_Podnos_2B14",
        "STAF_Podnos_2B14_Fleck",
        "STAF_KGB_B_MRAP_03_F",
        "STAF_KGB_B_MRAP_03_hmg_F",
        "STAF_KGB_B_MRAP_03_gmg_F",
        "STAF_KGB_B_MRAP_03_F_DES",
        "STAF_KGB_B_MRAP_03_hmg_F_DES",
        "STAF_KGB_B_MRAP_03_gmg_F_DES"
      };
      weapons[] = {};
      requiredAddons[] = {"cfp_cup_b_ger","CFP_B_DEARMY_WDL_WDL","CUP_AirVehicles_CH53E","CUP_AirVehicles_UH1H","CUP_WheeledVehicles_Dingo","CUP_TrackedVehicles_Leopard2","CUP_Weapons_StaticWeapons","BW_Choppers","BW_drohne","BW_Car","KGB_A3_Soft_F_MRAP_03","pook_EF2000","pook_EF2000_CUP"};
      requiredVersion = 1.62;
      author = "STAF";
      url = "http://www.stafclan.com";
    };
};
