_objs = _this select 0;

clearMagazineCargoGlobal _objs;
clearWeaponCargoGlobal _objs;
clearItemCargoGlobal _objs;
clearBackpackCargoGlobal _objs;

_objs addItemCargoGlobal ["ACE_salineIV",2];
_objs addItemCargoGlobal ["ACE_salineIV_250",4];
_objs addItemCargoGlobal ["ACE_salineIV_500",3];
_objs addItemCargoGlobal ["adv_aceSplint_splint",4];
_objs addItemCargoGlobal ["ACE_tourniquet",4];
_objs addItemCargoGlobal ["ACE_morphine",2];
_objs addItemCargoGlobal ["ACE_packingBandage",10];
_objs addItemCargoGlobal ["ACE_epinephrine",2];
_objs addItemCargoGlobal ["ACE_EarPlugs",2];
_objs addItemCargoGlobal ["ACE_quikclot",10];
_objs addItemCargoGlobal ["ACE_elasticBandage",10];
_objs addItemCargoGlobal ["ACE_fieldDressing",10];
_objs addItemCargoGlobal ["adv_aceCPR_AED",1];
_objs addItemCargoGlobal ["ACE_adenosine",2];
_objs addItemCargoGlobal ["ACE_bodyBag",2];
_objs addItemCargoGlobal ["TFAR_anprc152",1];
_objs addItemCargoGlobal ["ACE_CableTie",3];
_objs addItemCargoGlobal ["ACE_Flashlight_XL50",1];
_objs addItemCargoGlobal ["ACE_EntrenchingTool",1];
_objs addItemCargoGlobal ["ACE_wirecutter",1];
_objs addItemCargoGlobal ["ACE_DefusalKit",1];
_objs addItemCargoGlobal ["ACE_Clacker",1];
_objs addItemCargoGlobal ["ACE_UAVBattery",2];
