//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 164.138944 on Stable branch
//////////////////////////////////////////////////////////////////////////////////


class CfgFactionClasses {
    class STAF_PMC {
        displayName = "Security Tactics and Assault Force";
        side = 1;
        flag = "";
        icon = "\STAF\icon\staf_iconsmall.paa";
        priority = 1;
    };
};
