//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 166.139792 on Stable branch
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class WEST {
        class STAF_PMC {
            name = "Security Tactics and Assault Force";

            class Infantry {
                name = "Infantry";

                class STAF_Fireteam_1 {
                    name = "Fireteam (#1)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_mk18";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_mg_negev";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx_AT";
                    };
                };

                class STAF_Fireteam_2 {
                    name = "Fireteam (#2)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_mg_m249";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar_AT";
                    };
                };

                class STAF_Fireteam_3 {
                    name = "Fireteam (#3)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_scar";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_mg_negev";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_g36_AT";
                    };
                };

                class STAF_Fireteam_4 {
                    name = "Fireteam (#4)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_mx";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_mg_m249";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18_AT";
                    };
                };

                class STAF_Riflesquad_1 {
                    name = "Rifle Squad";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "STAF_teamleader_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_mg_m249";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_marksman_spar17";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_medic_scar";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18_GL";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx_AT";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                };

                class STAF_Recon_4 {
                    name = "Recon Sentry (#4)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_contractor_mx_GL";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                };

                class STAF_Recon_1 {
                    name = "Recon Sentry (#1)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                };

                class STAF_Recon_2 {
                    name = "Recon Sentry (#2)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_mg_m249";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                };

                class STAF_Recon_3 {
                    name = "Recon Sentry (#3)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_marksman_emr1";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                };
            };

            class SpecOps {
                name = "Special Forces";

                class STAF_Diverteam {
                    name = "Diver Team";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_diver_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mx";
                    };
                };

                class STAF_CBRN_MTP {
                    name = "CBRN Team (MTP)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_cbrn_mtp_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_cbrn_mtp_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_cbrn_mtp_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_cbrn_mtp_mx";
                    };
                };

                class STAF_CBRN_Woodland {
                    name = "CBRN (Woodland)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_cbrn_wd_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_cbrn_wd_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_cbrn_wd_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_cbrn_wd_mx";
                    };
                };

                class STAF_Diver_RHIB {
                    name = "Diver Team (RHIB)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_diver_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_rhib";
                    };
                };

                class STAF_Diver_SDV {
                    name = "Diver Team (SDV)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_diver_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_sdv";
                    };
                };

                class STAF_Diver_Boat {
                    name = "Diver Team (Assault Boat)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_diver_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_diver_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_rubberboat";
                    };
                };

                class STAF_Recon_UAV {
                    name = "Recon Team (UAV)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_mk18";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_uav_mx";
                    };
                };

                class STAF_Bodyguardteam {
                    name = "Bodyguard Team";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_bodyguard_mp5";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_bodyguard_p90";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_bodyguard_mp5";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_bodyguard_p90";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_client_american";
                    };
                };

                class STAF_Bodyguardteam_SUV {
                    name = "Bodyguard Team (SUV)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_bodyguard_mp5";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_bodyguard_p90";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_bodyguard_mp5";
                    };
                    class Unit3 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_client_american";
                    };
                    class Unit4 {
                        position[] = { 15 , -19 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_suv";
                    };
                };
            };

            class Motorized {
                name = "Motorized Infantry";

                class STAF_Mot_Inf {
                    name = "Motorized Team";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_mrap";
                    };
                };

                class STAF_Mot_Inf_HMG {
                    name = "Motorized HMG Team";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_mrap_hmg";
                    };
                };

                class STAF_Mot_Inf_LATV {
                    name = "Motorized Team (LATV)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_lsv";
                    };
                };

                class STAF_Mot_Inf_HMG_LATV {
                    name = "Motorized HMG Team (LATV)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_lsv_hmg";
                    };
                };

                class STAF_Mot_Inf_APC {
                    name = "Motorized Team (APC)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_contractor_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_contractor_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_m1117";
                    };
                };
            };

            class Support {
                name = "Support Infantry";

                class STAF_EOD {
                    name = "EOD Team";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_exp_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_exp_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_engineer_mx";
                    };
                };

                class STAF_EOD_MRAP {
                    name = "EOD Team (MRAP)";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_g36";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "STAF_exp_scar";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_exp_mk18";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_engineer_mx";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_mrap";
                    };
                };

                class STAF_MGTeam {
                    name = "MG Team";
                    side = 1;
                    faction = "STAF_PMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "STAF_teamleader_mk18";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_mg_m249";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "STAF_mg_negev";
                    };
                };
            };
        };
    };
};
