//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 164.138944 on Stable branch
//////////////////////////////////////////////////////////////////////////////////

class CfgWorlds {

	class GenericNames {

		class STAF_VIPNames {

			class FirstNames {
				turumai = "Turumai";
			};

			class LastNames
			{
				maru = "Maru";
				};
			};
		};
	};
