#include "\staf_pmc_main\fnc\loadout\defaults\assaultrifles.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\pistols.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\mg.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\marksmanrifles.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\smgs.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\launchers.hpp"

#include "\staf_pmc_main\fnc\loadout\defaults\goggles.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\divinggoggles.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\headgear.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\uniforms.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\vests.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\backpacks.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\divingbackpacks.hpp"

#include "\staf_pmc_main\fnc\loadout\defaults\wetsuits.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\rebreathers.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\helihelmets.hpp"
#include "\staf_pmc_main\fnc\loadout\defaults\nvgs.hpp"