//Init of the box and arsenal
_box = _this select 0;

//Itemlists

_weapons = [
  "SWOP_rk3",
  "swop_SE44Pistol",
  "swop_SE44cPistol",
  "swop_D93incinerator",
  "swop_f11d",
  "swop_f11dgrip",
  "swop_f11dext",
  "SWOP_FWMB10BlasterRifle",
  "Rangefinder"
];

_backpacks = [
  "SWOP_B_CloneDV",
  "SWOP_B_CloneDVa",
  "SWOP_FlameBFO",
  "SWOP_JetpackFO",
  "SWOP_snowpackFO",
  "SWOP_B_AssaultPackPC_Base",
  "SWOP_ImpSkyBackpack",
  "SWOP_B_ImSnowBackpack_Base",
  "SWOP_B_ImMedicSnowBackpack_Base",
  "SWOP_B_BlackBackpack_RTdv_Base",
  "SWOP_B_SnowBackpack_RTdv_Base"
];

_items = [
  "SWOP_NVChipClean",
  "SWOP_NVChip",
  "SWOP_NVChip2",
  "SWOP_ImpAdmBron",
  "SWOP_ImpCapBron",
  "SWOP_ciberimplant",
  "TFAR_fadak",
  "SWOP_FOCap",
  "SWOP_HelmEXETFO",
  "SWOP_StormTFO_Exec_F_CombatUniform",
  "SWOP_STFO_Exec_Vest",
  "SWOP_HelmFTFO",
  "SWOP_FOPil",
  "SWOP_HelmSnowTFO",
  "SWOP_HelmSTFO",
  "SWOP_StormTFO_F_CombatUniform",
  "SWOP_STFOVest",
  "SWOP_STFOVestHeavy",
  "SWOP_STFOVestPauldronR",
  "SWOP_STFOVestP",
  "SWOP_STFOVestPauldronB",
  "SWOP_STFOVestPauldronW",
  "ItemGPS",
  "SWOP_ImpGABron",
  "SWOP_ImpAdm_F_CombatUniform",
  "SWOP_ImpCapS",
  "SWOP_ImpCapB",
  "SWOP_ImpCap",
  "SWOP_ImpCapG",
  "SWOP_ImpKr_F_CombatUniform",
  "SWOP_ImpN_F_CombatUniform",
  "SWOP_ImpOf_F_CombatUniform",
  "SWOP_ImpLt_F_CombatUniform",
  "SWOP_TIEpilotB_F_CombatUniform",
  "SWOP_empire_pilot_unif__F_CombatUniform",
  "SWOP_TIEpilot_F_CombatUniform",
  "SWOP_Empire_pilot_vest",
  "ItemMap",
  "ItemWatch",
  "ToolKit"
];

_magazines = [
  "SWOP_ca87buckshot_Mag",
  "SWOP_CA87Concussion_Mag",
  "SW_cj9_BlasterRifle_Mag",
  "SWOP_DH17BlasterRifle_Mag",
  "SWOP_DLT19BlasterRifle_Mag",
  "SWOP_DLT19DBlasterRifle_Mag",
  "SWOP_DLT19XBlasterRifle_Mag",
  "SWOP_E11SBlasterRifle_Mag",
  "swop_e11b_Mag",
  "swop_e11_Mag",
  "E11Stun_Mag",
  "SWOP_E22BlasterRifle_Mag",
  "SWOP_EE4BlasterRifle_Mag",
  "BTX42_Flamethrower_mag",
  "BTX42_Flamethrower_mag400",
  "BTX42_Flamethrower_mag300",
  "BTX42_Flamethrower_mag200",
  "BTX42_Flamethrower_mag100",
  "BTX42_Flamethrower_mag050",
  "relbyv10_Mag",
  "SWOP_relbyv10grenade_Mag",
  "SWOP_rt97cBlasterRifle_Mag",
  "SW_Scattergun_Mag",
  "SW_iondisruptor_BlasterRifle_Mag",
  "SWOP_T21B_BlasterRifle_Mag",
  "SWOP_T21BlasterRifle_Mag",
  "SWOP_HeavyRepeater_Mag",
  "SWOP_HeavyRepeaterConcussion_Mag",
  "SWOP_WESTARM5_Mag",
  "WestarM5grenade_Mag",
  "SWOP_DT29Pistol_Mag",
  "SWOP_K16Pistol_Mag",
  "SWOP_rk3_Mag",
  "SWOP_scoutPistol_Mag",
  "SWOP_se14cPistol_Mag",
  "SWOP_x8Pistol_Mag",
  "D93incinerator_Mag",
  "swop_f11d_Mag",
  "SWOP_f11d_Mag",
  "SWOP_f11dStun_Mag",
  "E11Stun_Mag",
  "SWOP_FWMB10BlasterRifle_Mag",
  "SWOP_rk3_Mag",
  "SWOP_se44Pistol_Mag",
  "SWOP_bacta_G",
  "SWOP_BCCKtermimploder_G",
  "SWOP_BCCKstermDet_G",
  "swop_termDetDT_G",
  "SWOP_termDet_G",
  "SWOP_termDet_Gm",
  "SWOP_SCAR_DioxisGM",
  "SWOP_SCAR_EMP_GrenadeGM",
  "swop_EMP_Remote_Mag",
  "TermMine_Mag",
  "TermMineB_Mag",
  "TermMineC_Mag",
  "swop_mag_flashbang",
  "swop_mag_gimpact",
  "swop_mag_incendiary",
  "swop_SmokeShell",
  "SWOPthrowablectype",
  "SWOPthrowableExplosive",
  "O_IR_Grenade",
  "DemoCharge_Remote_Mag",
  "SatchelCharge_Remote_Mag",
  "SmokeShell",
  "SW_PersonalShield_Mag",
  "SW_halfshield_Mag",
  "SW_SquadShield_Mag",
  "SW_SquadShield_magCARGA"
];

_ACE = [
  "ACE_VMM3",
  "ACE_fieldDressing",
  "ACE_packingBandage",
  "ACE_elasticBandage",
  "ACE_tourniquet",
  "ACE_morphine",
  "ACE_adenosine",
  "ACE_atropine",
  "ACE_epinephrine",
  "ACE_plasmaIV",
  "ACE_plasmaIV_500",
  "ACE_plasmaIV_250",
  "ACE_salineIV",
  "ACE_salineIV_500",
  "ACE_salineIV_250",
  "ACE_bloodIV",
  "ACE_bloodIV_500",
  "ACE_bloodIV_250",
  "ACE_quikclot",
  "ACE_personalAidKit",
  "ACE_surgicalKit",
  "ACE_bodyBag",
  "ACE_wirecutter",
  "ACE_Sandbag_empty",
  "ACE_SpraypaintBlack",
  "ACE_SpraypaintRed",
  "ACE_SpraypaintBlue",
  "ACE_SpraypaintGreen",
  "ACE_EntrenchingTool",
  "ACE_Tripod",
  "ACE_CableTie",
  "ACE_Chemlight_Shield",
  "ACE_Clacker",
  "ACE_M26_Clacker",
  "ACE_DefusalKit",
  "ACE_DeadManSwitch",
  "ACE_Flashlight_MX991",
  "ACE_Flashlight_KSF1",
  "ACE_Flashlight_XL50",
  "ACE_EarPlugs",
  "adv_aceSplint_splint"
];

_attachments = [];
{
    {
        _attachments pushBackUnique _x;
    } forEach ([_x] call CBA_fnc_compatibleItems);
} forEach _weapons;

//Adding Itemlists to the Arsenal
[_box,(_items + _backpacks + _magazines + _weapons + _ACE + _attachments),true] call ace_arsenal_fnc_initBox;

[_box,["<img image='\a3\ui_f\data\IGUI\Cfg\simpleTasks\types\box_ca.paa' /> Open Arsenal",{[(_this select 0), player,false] call ace_arsenal_fnc_openBox;}]] remoteExec ["addAction",0,true];
