_objs = _this select 0;

clearMagazineCargoGlobal _objs;
clearWeaponCargoGlobal _objs;
clearItemCargoGlobal _objs;
clearBackpackCargoGlobal _objs;

_objs addItemCargoGlobal ["ACE_salineIV",3];
_objs addItemCargoGlobal ["ACE_salineIV_250",9];
_objs addItemCargoGlobal ["ACE_salineIV_500",6];
_objs addItemCargoGlobal ["ACE_splint",6];
_objs addItemCargoGlobal ["ACE_surgicalKit",1];
_objs addItemCargoGlobal ["ACE_tourniquet",10];
_objs addItemCargoGlobal ["ACE_morphine",5];
_objs addItemCargoGlobal ["ACE_packingBandage",20];
_objs addItemCargoGlobal ["ACE_epinephrine",5];
_objs addItemCargoGlobal ["ACE_EarPlugs",5];
_objs addItemCargoGlobal ["ACE_quikclot",20];
_objs addItemCargoGlobal ["ACE_elasticBandage",20];
_objs addItemCargoGlobal ["ACE_fieldDressing",20];
_objs addItemCargoGlobal ["ACE_adenosine",5];
_objs addItemCargoGlobal ["ACE_bodyBag",2];
_objs addItemCargoGlobal ["ACE_personalAidKit",2];
_objs addItemCargoGlobal ["kat_X_AED",1];
_objs addItemCargoGlobal ["kat_guedel",2];
_objs addItemCargoGlobal ["kat_larynx",2];
_objs addItemCargoGlobal ["kat_Pulseoximeter",2];
_objs addItemCargoGlobal ["kat_stethoscope",2];
_objs addItemCargoGlobal ["kat_IV_16",10];
_objs addItemCargoGlobal ["kat_aatKit",1];
_objs addItemCargoGlobal ["kat_amiodarone",2];
_objs addItemCargoGlobal ["kat_CarbonateItem",2];
_objs addItemCargoGlobal ["kat_EACA",2];
_objs addItemCargoGlobal ["kat_etomidate",2];
_objs addItemCargoGlobal ["kat_fentanyl",2];
_objs addItemCargoGlobal ["kat_flumazenil",2];
_objs addItemCargoGlobal ["kat_ketamine",2];
_objs addItemCargoGlobal ["kat_lidocaine",2];
_objs addItemCargoGlobal ["kat_lorazepam",2];
_objs addItemCargoGlobal ["kat_naloxone",2];
_objs addItemCargoGlobal ["kat_nalbuphine",2];
_objs addItemCargoGlobal ["kat_nitroglycerin",2];
_objs addItemCargoGlobal ["kat_norepinephrine",2];
_objs addItemCargoGlobal ["kat_phenylephrine",2];
_objs addItemCargoGlobal ["kat_TXA",2];