//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class STAF_pmc_headgear {
      units[] = {};
      weapons[] = {
        "STAF_H_HelmetSpecB_white",
        "STAF_H_HelmetSpecB_white_hex",
        "STAF_H_HelmetSpecB_white_mcam",
        "STAF_H_HelmetSpecB_white_splinter",
        "STAF_H_HelmetB_white",
        "STAF_H_HelmetB_white_hex",
        "STAF_H_HelmetB_white_mcam",
        "STAF_H_HelmetB_white_splinter",
        "STAF_H_HelmetIA_white",
        "STAF_H_HelmetIA_white_hex",
        "STAF_H_HelmetIA_white_mcam",
        "STAF_H_HelmetIA_white_splinter",
        "STAF_H_HelmetSpecB_Pete_Arid",
        "STAF_H_HelmetSpecB_Pete_Lush",
        "STAF_H_HelmetSpecB_Pete_Winter",
        "STAF_H_Watchcap_white",
        "STAF_H_Beanie_White",
        "STAF_h_airframe_01_white",
        "STAF_h_airframe_01_goggles_white",
        "STAF_h_airframe_02_white",
        "STAF_h_airframe_02_goggles_white",
        "STAF_h_airframe_03_white",
        "STAF_h_airframe_03_goggles_white",
        "STAF_h_airframe_04_white",
        "STAF_h_airframe_04_goggles_white",
        "STAF_h_airframe_05_white",
        "STAF_h_airframe_05_goggles_white",
        "STAF_h_airframe_06_white",
        "STAF_h_airframe_06_goggles_white",
        "STAF_h_airframe_01_white_digi",
        "STAF_h_airframe_01_goggles_white_digi",
        "STAF_h_airframe_02_white_digi",
        "STAF_h_airframe_02_goggles_white_digi",
        "STAF_h_airframe_03_white_digi",
        "STAF_h_airframe_03_goggles_white_digi",
        "STAF_h_airframe_04_white_digi",
        "STAF_h_airframe_04_goggles_white_digi",
        "STAF_h_airframe_05_white_digi",
        "STAF_h_airframe_05_goggles_white_digi",
        "STAF_h_airframe_06_white_digi",
        "STAF_h_airframe_06_goggles_white_digi",
        "STAF_h_airframe_01_white_hex",
        "STAF_h_airframe_01_goggles_white_hex",
        "STAF_h_airframe_02_white_hex",
        "STAF_h_airframe_02_goggles_white_hex",
        "STAF_h_airframe_03_white_hex",
        "STAF_h_airframe_03_goggles_white_hex",
        "STAF_h_airframe_04_white_hex",
        "STAF_h_airframe_04_goggles_white_hex",
        "STAF_h_airframe_05_white_hex",
        "STAF_h_airframe_05_goggles_white_hex",
        "STAF_h_airframe_06_white_hex",
        "STAF_h_airframe_06_goggles_white_hex",
        "STAF_h_airframe_01_white_mcam",
        "STAF_h_airframe_01_goggles_white_mcam",
        "STAF_h_airframe_02_white_mcam",
        "STAF_h_airframe_02_goggles_white_mcam",
        "STAF_h_airframe_03_white_mcam",
        "STAF_h_airframe_03_goggles_white_mcam",
        "STAF_h_airframe_04_white_mcam",
        "STAF_h_airframe_04_goggles_white_mcam",
        "STAF_h_airframe_05_white_mcam",
        "STAF_h_airframe_05_goggles_white_mcam",
        "STAF_h_airframe_06_white_mcam",
        "STAF_h_airframe_06_goggles_white_mcam",
        "STAF_h_airframe_01_black",
        "STAF_h_airframe_01_goggles_black",
        "STAF_h_airframe_02_black",
        "STAF_h_airframe_02_goggles_black",
        "STAF_h_airframe_03_black",
        "STAF_h_airframe_03_goggles_black",
        "STAF_h_airframe_04_black",
        "STAF_h_airframe_04_goggles_black",
        "STAF_h_airframe_05_black",
        "STAF_h_airframe_05_goggles_black",
        "STAF_h_airframe_06_black",
        "STAF_h_airframe_06_goggles_black",
        "STAF_veil_black",
        "STAF_veil_tan",
        "STAF_veil_white",
        "STAF_empty_goggles"
      };
      requiredAddons[] = {};
      requiredVersion = 1.62;
      author = "STAF";
      url = "http://www.stafclan.com";
    };
};
