//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
    class STAF_pmc_infantry {
      units[] = {
        "STAF_contractor_g36",
        "STAF_contractor_scar",
        "STAF_contractor_mk18",
        "STAF_contractor_mx",
        "STAF_contractor_g36_GL",
        "STAF_contractor_scar_GL",
        "STAF_contractor_mk18_GL",
        "STAF_contractor_mx_GL",
        "STAF_contractor_g36_AT",
        "STAF_contractor_scar_AT",
        "STAF_contractor_mk18_AT",
        "STAF_contractor_mx_AT",
        "STAF_medic_g36",
        "STAF_medic_scar",
        "STAF_medic_mk18",
        "STAF_medic_mx",
        "STAF_marksman_spar17",
        "STAF_marksman_ak12",
        "STAF_marksman_emr1",
        "STAF_mg_m249",
        "STAF_mg_negev",
        "STAF_sharpshooter_gm6",
        "STAF_sharpshooter_mar10",
        "STAF_sharpshooter_m200",
        "STAF_teamleader_g36",
        "STAF_teamleader_scar",
        "STAF_teamleader_mk18",
        "STAF_teamleader_mx",
        "STAF_exp_g36",
        "STAF_exp_scar",
        "STAF_exp_mk18",
        "STAF_exp_mx",
        "STAF_uav_g36",
        "STAF_uav_scar",
        "STAF_uav_mk18",
        "STAF_uav_mx",
        "STAF_engineer_g36",
        "STAF_engineer_scar",
        "STAF_engineer_mk18",
        "STAF_engineer_mx",
        "STAF_diver_g36",
        "STAF_diver_scar",
        "STAF_diver_mk18",
        "STAF_diver_mx",
        "STAF_cbrn_mtp_g36",
        "STAF_cbrn_mtp_scar",
        "STAF_cbrn_mtp_mk18",
        "STAF_cbrn_mtp_mx",
        "STAF_cbrn_wd_g36",
        "STAF_cbrn_wd_scar",
        "STAF_cbrn_wd_mk18",
        "STAF_cbrn_wd_mx",
        "STAF_bodyguard_mp5",
        "STAF_bodyguard_p90",
        "STAF_helipilot",
        "STAF_copilot",
        "STAF_helipilot_heavy",
        "STAF_copilot_heavy",
        "STAF_pilot",
        "STAF_boss",
        "STAF_client_american",
        "STAF_client_british",
        "STAF_client_chinese",
        "STAF_client_african",
        "STAF_client_greek",
        "STAF_client_scientist",
        "STAF_client_un"
      };
      weapons[] = {};
      requiredAddons[] = {};
      requiredVersion = 1.62;
      author = "STAF";
      url = "http://www.stafclan.com";
    };
};
